config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/about", to: "pages#about"
  get "/legalnotice", to: "pages#legalnotice"
  get "/dataprotection", to: "pages#dataprotection"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :firstName, :lastName, :address, :postalCode, :city, :country, :email, :reason, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def legalnotice
  end

  def dataprotection
  end

  def signup
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "User was successfully registered."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:firstName, :lastName, :address, :postalCode, :city, :country, :email, :reason)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
  <meta charset="utf-8">
    <title>DEB e.V.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/fontawesome.css"
  integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong><%= t 'About us' %></strong></h1>
  </div>
</div>

<div class="text-container">
  <div>
    <h2>
    Digital Education Bridge e.V. is a fully remote NGO and registered as an association in Berlin, Germany.
    </h2>
    <h2>
    DEB's aim is to offer free remote education to batches of promising teenagers in developing countries.
    </h2>
    <h2 class="title-about">
    Who we are
    </h2>
    <p>
    Digital Education Bridge has been founded by a group of young Europeans and Latin Americans. We aim to offer new perspectives and opportunities to promising children and teenagers from developing countries. Our members believe in creating prosperity for people through the power of education.
    </p>

    <h2 class="title-about">
    History
    </h2>
    <p>
    The idea of offering free remote classes to children was born during the global pandemic in 2020. As universities and schools switched to remote classes, it became clear that remote education is possible if necessary.

    Having experienced first-hand that many teenagers in Nicaragua lack the opportunity of learning English, the chairman of NGO decided to organise a remote English class for 9 children. This pilot project turned out to be successful - but to finance and scale future batches, the incorporation of an NGO was needed.

    DEB’s first projects in 2024 are a continuation of the English class, offering the A1 level three times a week for 3 months to chosen batches of teenagers.
    </p>

  </div>
</div>

app/views/pages/dataprotection.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong>Data protection declaration</strong></h1>
  </div>
</div>

<div class="text-container">
  <div class="textcontent">
    <h2>
    Datenschutzerklärung
    </h2>

    <p>
    Digital Education Bridge e.V. hat satzungsgemäß die Aufgabe, die Entwicklungszusammenarbeit mithilfe von kostenlosem online-Unterricht zu fördern. Damit wir diese Aufgabe wahrnehmen können, verarbeiten wir personenbezogene Daten von Ihnen. Der Schutz Ihrer personenbezogenen Daten ist uns ein wichtiges Anliegen. Wir verarbeiten diese Daten gemäß Bundesdatenschutzgesetz, EU-Datenschutzgrundverordnung (DSGVO) und Telemediengesetz.
    </p>
    <p>
    Diese Webseite wird vom Digital Education Bridge e.V. betrieben. Er ist Verantwortlicher im Sinne der datenschutzrechtlichen Vorschriften. Bei Fragen und Anregungen hinsichtlich unseres Umgangs mit Ihren Daten wenden Sie sich bitte an die Kontaktadresse in unserem Impressum oder unsere Beauftragte für den Datenschutz unter: info@digitaleducationbridge.org
    </p>

    <p><strong>Umgang mit personenbezogenen Daten</strong></p>
    <p>
    Wir verarbeiten Ihre personenbezogene Daten, z. B. Name, Kontaktdaten, IP-Adresse oder sonstige Angaben, die mit Ihrer Identität in Verbindung stehen, auf der Grundlage des Art. 6 DSGVO zur Wahrung unseres berechtigten Interesses an der Erfüllung unserer Satzungsaufgabe, zur Erfüllung einer Vereinbarung mit Ihnen oder soweit Sie eingewilligt haben. Wir verwenden Ihre Daten ausschließlich für den Zweck, zu dem Sie uns diese überlassen haben.
    </p>
    <p>
    Bei der Kontaktaufnahme über unser Kontaktformular (verschlüsselte Übertragung) oder per E-Mail werden Ihre Angaben zwecks Bearbeitung der Anfrage sowie für Rückfragen gespeichert.
    </p>
    <p>
    Wenn Sie sich bei uns für eine Mitgliedschaft bewerben, werden Ihre Angaben ausschließlich zur Bearbeitung Ihrer Bewerbung verwendet und nicht an Dritte weitergegeben. Bitte beachten Sie, dass Bewerbungen, die Sie uns per E-Mail senden, unverschlüsselt übertragen werden.
    </p>

    <p><strong>Recht auf Auskunft, Berichtigung und Löschung</strong></p>
    <p>
    Sie haben das Recht, unentgeltlich Auskunft darüber zu erhalten, ob und welche personenbezogenen Daten wir von Ihnen gespeichert haben, Art. 15 DSGVO. Sollten wir Ihre persönlichen Daten unrichtig gespeichert haben, können Sie die Angaben berichtigen lassen. In den Fällen, in denen wir Ihre persönlichen Daten zur Erfüllung unseres Satzungszwecks gemäß Art. 6 Abs. 1 f) DSGVO verarbeiten, können Sie begründeten Widerspruch gegen diese Verarbeitung einlegen. Soweit keine gesetzlichen Aufbewahrungspflichten entgegen stehen, können Sie jederzeit die Löschung Ihrer Daten verlangen, Art. 17 f. DSGVO. Bitte kontaktieren Sie uns unter: info@digitaleducationbridge.org.
    </p>

    <p><strong>Widerruf der Einwilligung</strong></p>
    <p>
    Sofern Sie uns eine Einwilligung zur Verarbeitung Ihrer persönlichen Daten erteilt haben, z. B. bei der Anmeldung für unseren elektronischen Newsletter, oder eine Mitgliedschaft, können Sie diese gemäß Art. 7 Abs. 3 DSGVO jederzeit mit Wirkung für die Zukunft widerrufen. Richten Sie Ihren formlosen Widerruf an: info@digitaleducationbridge.org
    </p>

    <p><strong>Weitergabe an Dritte</strong></p>
    <p>
    Eine Weitergabe Ihrer Daten an Dritte erfolgt nicht.
    </p>

    <p><strong>Verwendung von "Cookies"</strong></p>
    <p>
    Wie viele andere Internet-Anbieter verwenden wir im Rahmen unseres Online-Angebotes so genannte Cookies. "Cookies" sind Dateien, die für die Dauer Ihres Besuchs auf unserer Webseite auf Ihrem Computer, Smartphone o. ä., gespeichert werden, um festzuhalten, wie Sie sich als Nutzer auf unserer Webseite bewegen. Sie tragen dazu bei, dass Sie z. B. reibungslos navigieren, mehrstufige Bestellvorgänge abwickeln können oder die gewählte Schriftgröße beim Wechsel auf Unterseiten unverändert bleibt.
    </p>
    <p>
    Gängige Web-Browser sind standardmäßig so eingestellt, dass sie "Cookies" akzeptieren. Sie können diese Einstellung verändern, sodass "Cookies" abgelehnt oder vorher eine Bestätigung von Ihnen erfragt wird. Wenn Sie "Cookies" ablehnen, kann es passieren, dass Sie bestimmte Funktionen unseres Online-Angebots nicht mehr vollumfänglich nutzen können.
    </p>

    <p><strong>Beschwerderecht</strong></p>
    <p>
    Bei offenen Fragen zum Schutz Ihrer personenbezogenen Angaben, die Sie dem Digital Education Bridge e.V. überlassen haben bzw. die der Digital Education Bridge e.V. von Ihnen verarbeitet, nehmen Sie bitte Kontakt mit uns auf unter: info@digitaleducationbridge.org damit wir den Schutz Ihrer Daten prüfen und durchgängig gewährleisten können.
    </p>

    <p>
    Wenn Sie der Ansicht sind, der Digital Education Bridge e.V. verstoße bei der Verarbeitung Ihrer personenbezogenen Daten gegen datenschutzrechtliche Vorschriften, haben Sie das Recht auf Beschwerde bei einer Aufsichtsbehörde. Zuständige Aufsichtsbehörde ist die Berliner Beauftragte für den Datenschutz und Informationsfreiheit, Friedrichstraße 219, 10969 Berlin.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner-home" background-color="green">
  <div class="container">
   <div class="deb-slogan"><%= t '.slogan_html' %></div>
  </div>
</div>

<div class="navbox-mission">

  <div class="row">

    <div class="debmission-text col-3">
      <div class="imgnav">
        <img src="<%= asset_path('nicaraguachildstudying.jpg') %>" alt="Child studying" class="img-fluid">
      </div>
    </div>

    <div class="mission-text col-9">
      <p class="mission-title">Our Mission</p>
      <p class="opp-text"><strong>Creating Opportunities</strong></p>
      <p class="deb-text">Digital Education Bridge leverages the internet to overcome local education gaps in developing countries. Our experienced teachers give weekly remote classes to small batches of promising studentes. We are a 100% remote NGO dedicated to reduce poverty by creating opportunities through education. </p>
    </div>

  </div>

  <div class="row visionrow">

    <div class="debvision-text col-9">
      <p class="vision-title">Our Vision</p>
      <p class="ed-text"><strong>Education to empower</strong></p>
      <p class="bio-text">We believe in the power of education. Our aim is to unlock opportunities for thousands of teenagers in developing countries to learn languages, study abroad, acquire high-demand digital skills, and create better lives for their families. We're united by the conviction that education is the key to a brighter tomorrow!</p>
    </div>

    <div class="zoomcall col-3">
      <div class="imgzoom">
        <img src="<%= asset_path('proyectoingles.jpg') %>" alt="zoom meeting" class="img-fluid">
      </div>
    </div>

  </div>
</div>

app/views/pages/legalnotice.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong>Legal notice</strong></h1>
  </div>
</div>

<div class="text-container">
  <div class="textcontent">
    <h2>
    Impressum
    </h2>
    <p>
    Digital Education Bridge e.V.
    </p>
    <p>
    Gegründet am 12.10.2023 in Berlin.
    </p>
    <p>
    Rechtssitz des Vereins ist Berlin.
    </p>
    <p>
    Satzungsgemäße Aufgabe des Vereins und seiner Mitglieder ist die Förderung der Entwicklungszusammenarbeit. Dieser Zweck wird verwirklicht durch die
    Förderung von Bildungswesen und bevölkerungspolitischen Maßnahmen durch das
    kostenlose Angebot digitaler oder analoger Bildungs- und Unterstützungsangebote in
    Entwicklungsländern, zur Förderung der persönlichen und beruflichen Entwicklung
    der Begünstigten.
    </p>
    <p>
    Email: info@digitaleducationbridge.org
    </p>
    <p>
    Vereinsvorstand:
    </p>
    <p>
    Vorstandsvorsitzender: Nikolai Regehr
    </p>
    <p>
    Vizevorstandsvorsitzende: Fahrina Bestvater
    </p>
    <p>
    Schatzmeister: Maxime Fischer
    </p>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row align-items-center">
      <div class="col text-left">
        <%= link_to do %>
          <%= image_tag "DEB-preliminary-logo.png", alt: "DEB Logo", style: "width: 50px; height: auto;" %>
        <% end %>
      </div>

      <div class="col text-center">
        <div class="footer-links">
          <%= link_to "Legal notice", legalnotice_path, class: "nav-link" %>
          <span class="separator"> | </span>
          <%= link_to "Data declaration", dataprotection_path, class: "nav-link" %>
        </div>
      </div>

      <div class="col text-right">
        <p>contact: info@digitaleducationbridge.org</p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 text-center copyright-text">
        <p>© 2024 Digital Education Bridge e.V. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-deb">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <img src="<%= asset_path('DEB-preliminary-logo') %>" alt="deb-logo">
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
          </li>

          <%= link_to t('global.navbar.apply'), signup_path, class: "btn btn-green" %>

         <li class="nav-item dropdown">
          <span class="fa-solid fa-bars" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
          <div class="dropdown-menu dropdown-menu-end languages-dropdown" aria-labelledby="navbarDropdown">
            <%= link_to t('global.navbar.about'), about_path, class: "dropdown-item" %>
            <span class="languages__header">Languages</span>
            <div class="flag-images">
              <img src="https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg" alt="German Flag">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png" alt="UK Flag">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/1200px-Bandera_de_Espa%C3%B1a.svg.png" alt="Spain Flag">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1200px-Flag_of_Portugal.svg.png" alt="Portugal Flag">
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
  <div class="container p-4" style="background-color: #f0f0f0">
    <div class="row justify-content-center">
      <%= simple_form_for '', url: 'https://script.google.com/macros/s/AKfycbxlPwmxTbnmoDdrY89vr7h709dk_-tRI3FB_oybrT06Fe8Plj76EoAUD4oYCuD9_v3uxw/exec', method: :post, html: { class: 'col-md-8' } do |f| %>

        <div class="Form">
          <div class="row">
            <div class="col-md-6">
              <%= f.input :First_name, label: 'Name', required: true, placeholder: 'First name', input_html: { class: 'form-control mb-3' } %>
            </div>
            <div class="col-md-6">
              <%= f.input :Last_name, required: true, placeholder: 'Last name', input_html: { class: 'form-control mb-3' } %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <%= f.input :Street_and_street_number, label: 'Address', required: true, placeholder: 'Street & street number', input_html: { class: 'form-control mb-3' } %>
            </div>
            <div class="col-md-6">
              <%= f.input :Postal_code, required: true, placeholder: 'Postal code', input_html: { class: 'form-control mb-3' } %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :City, required: true, placeholder: 'City', input_html: { class: 'form-control mb-3' } %>
            </div>
            <div class="col-md-6">
              <%= f.input :Country, required: true, placeholder: 'Country', input_html: { class: 'form-control mb-3' } %>
            </div>
          </div>
          <div class="col-md-12">
            <%= f.input :Email, label: 'Email', required: true, placeholder: 'Email address', input_html: { class: 'form-control-lg mb-3' } %>
          </div>
          <div class="col-md-12">
            <%= f.input :Your_reason_to_join, label: 'Why do you want to join us as a member?', as: :text, required: true, placeholder: 'Write more than 100 characters', input_html: { class: 'form-control-lg mb-3', rows: 3 } %>
          </div>
          <div class="col-md-12">
            <%= f.submit t('global.forms.submit'), class: 'btn btn-primary col-md-12' %>
          </div>
        </div>
      <% end %>

    </div>
  </div>

app/views/users/new.html.erb
<div class="banner" background-color="green">
  <h1><strong>Support Digital Education Bridge</strong></h1>
</div>

<div class="signup-content">
  <div class="signup-header">
    <h2>Become a member of the Digital Education Bridge e.V.</h2>
    <p>Join us to get involved in projects, follow our development and support us in scaling DEB.</p>
    <p>Currently the association does not require membership fees.</p>
  </div>

  <%= render 'form' %>

  <div class="donate-header" style="margin-top: 20px;">
    <h2>Donate to Digital Education Bridge e.V.</h2>
    <div class="donate-content p-4" style="background-color: #f0f0f0">
      <p class="comingsoon">         Coming soon...</p>
    </div>
  </div>
</div>